### ISSUE TITLE
Hybridbar does not find  gsettings schema 'io.elementary.desktop.wingpanel.datetime'

### ISSUE THREAD

**Issue by indicozy** [hcsubser/hybridbar#1]
Hi, I was interested in your repo and tried to use it.
I installed all dependencies listed as well as dependencies for building indicators (distro: Arch).
After an installation and just before building indicators everything worked fine, i.e. it was just an empty space without any indicator.
After building indicators and starting hybridbar, this message came in:
```
** (hybridbar:15668): WARNING **: 15:11:46.555: gtk-layer-shell v0.6.0 may not work on GTK v3.24.29. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md

(hybridbar:15668): Gdk-CRITICAL **: 15:11:46.555: gdk_monitor_get_geometry: assertion 'GDK_IS_MONITOR (monitor)' failed

(hybridbar:15668): GLib-GIO-ERROR **: 15:11:46.584: Settings schema 'io.elementary.desktop.wingpanel.datetime' is not installed
zsh: trace trap (core dumped)  hybridbar
```
I'm not good at coding, but afaik I can enter dimensions of my monitors manually.

Distro: Arch
DE used while building: Cinnamon (I coudnt configure pkexec in Sway, so I logged in to my backup DE)

**Comment by hcsubser** [comment]
Ah yes this was a mistake on my part, should be fixed now in the main branch.
Try building now from master and tell me if you have the same problem
