### ISSUE TITLE
Questions regarding Maintenance and upkeeping..

### ISSUE THREAD

**Issue by ghost** [hcsubser/hybridbar#11]
Hey there @rharter  is there any assurance this project will be maintained in the future i wish to use this awesome project in my new project Mira Desktop Environment based atop Mir, but i wanna ask will this be maintained in the future,  i would love this project being part of the Mira Desktop Environment, assurance will be really grateful.

**Comment by rharter** [comment]
Not from me. I'm a random guy that submitted a couple of PRs a couple years ago, but I don't own this repo. Probably better to ask @hcsubser (or look at the commit and PR history 🫤).

**Comment by CapeCrusader321** [comment]
Ooops, @hcsubser  any comment on this question ??

**Comment by hcsubser** [comment]
Well, @CapeCrusader321  I am using hybridbar as is. It is pretty much done for me as it is working as intended. that being said if something ever stops working I will look into fixing it. Also if someone ever decides to make a PR that adds new features I will gladly merge it if it works.
