### ISSUE TITLE
In the screenshot, what is the theme? and the icon pack?

### ISSUE THREAD

**Issue by subnut** [hcsubser/hybridbar#7]
I love the icon packs. Which icon pack is it?  
Also, the theme... which theme is it?

One more thing -  I see an application called _HybridFM_. I couldn't find it on google. Where did you get it from?

**Comment by hcsubser** [comment]
Sorry, for taking so long to reply

theme: Orchis-light
icons: korla-light

HybridFM is a file manager I've worked on, it is forked from PCmanFM and I've been using it lately. However you cannot find it anywhere on Google(i dod not upload it) becaouse it is not really that usable without a few quirks, also codebase is a complete mess currently. I will let you know if i ever decide to upload it to github
