### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by basicfunc** [hcsubser/hybridbar#8]
Hey dev!
Just wanted to try out this on Void Linux, the bar compiles completely fine but indicators not. They ask for some library related to evolution calendar, I guess. Can you please make it available on either Arch Linux or Void Linux.  OR can just provide a list of all dependencies which are required by indicators. So, I can try to make a template.

**Comment by hcsubser** [comment]
These are the dependencies for the calendar(these are debian\ubuntu names it may be called a little bit different on arch, I dont use it so i dont know the exact name though I am pretty sure it is available in repos):

    gobject-introspection
    libecal1.2-dev
    libedataserver1.2-dev
    libical-dev
    libhybridbar-dev
    meson
    valac >= 0.40.3


inside this git directory there is indicators directory and every indicator has their own readme inside of those directories with dependencies listed.

I will eventually when i come back to this project make it possible to compile everything including indicators using one single meson.build file

**Comment by basicfunc** [comment]
> These are the dependencies for the calendar(these are debian\ubuntu names it may be called a little bit different on arch, I dont use it so i dont know the exact name though I am pretty sure it is available in repos):
> 
> ```
> gobject-introspection
> libecal1.2-dev
> libedataserver1.2-dev
> libical-dev
> libhybridbar-dev
> meson
> valac >= 0.40.3
> ```
> 
> inside this git directory there is indicators directory and every indicator has their own readme inside of those directories with dependencies listed.
> 
> I will eventually when i come back to this project make it possible to compile everything including indicators using one single meson.build file

Thanks dev. Looks like libecal is not provided by my distro. I'll try compiling it myself. Will let you know if any error appears.
